### ISSUE TITLE
[Bug]: Timeout Error caught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mnedelko** [metaplex-foundation/gumdrop#7]
### Which package is this bug report for?

cli

### Issue description

I executed the following command

ts-node ./packages/cli/src/gumdrop-cli.ts create -k <SellerWallet>.json --claim-integration transfer --transfer-mint <Token Key Pair> --distribution-method wallets --distribution-list dislist.json

### Relevant log output

```shell
Parsed options: {
  env: 'devnet',
  keypair: '...',
  host: 'https://gumdrop.metaplex.com/',
  claimIntegration: 'transfer',
  transferMint: '...',
  distributionMethod: 'wallets',
  distributionList: 'dislist.json'
}
wallet public key: ...
temporal signer: ...
Hashes 0 [
  <Buffer ...>
]
writing base to .log/devnet/9kAUVjnGaRdqTZjAkzZs44cTnJvAwxxsR34vVyRC9WDw/id.json
writing claims to .log/devnet/9kAUVjnGaRdqTZjAkzZs44cTnJvAwxxsR34vVyRC9WDw/urls.json
Timeout Error caught TypeError: Cannot read property '0' of undefined
    at awaitTransactionSignatureConfirmation (/Users/mnedelko/Documents/nftproject/gumdrop/gumdrop/packages/cli/src/helpers/transactions.ts:209:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendSignedTransaction (/Users/mnedelko/Documents/nftproject/gumdrop/gumdrop/packages/cli/src/helpers/transactions.ts:48:26)
    at async Command.<anonymous> (/Users/mnedelko/Documents/nftproject/gumdrop/gumdrop/packages/cli/src/gumdrop-cli.ts:294:26)
(node:27814) UnhandledPromiseRejectionWarning: Error: Transaction failed: Instruction: NewDistributor
    at sendSignedTransaction (/Users/mnedelko/Documents/nftproject/gumdrop/gumdrop/packages/cli/src/helpers/transactions.ts:83:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.<anonymous> (/Users/mnedelko/Documents/nftproject/gumdrop/gumdrop/packages/cli/src/gumdrop-cli.ts:294:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27814) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27814) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Operating system

Mac OS Big Sur 11.6.4

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by mnedelko** [comment]
It is proably worthwhile mentioning that the transaction appears to fail with the following instruction:

> Transaction failed: Instruction: NewDistributor

I tried to find what this might mean but was unable to do so.

**Comment by heep-jay** [comment]
i am also having the same poblem.

**Comment by mnedelko** [comment]
I was able to create a workaround by using an older version of megaplex, where gumdrop was still part of the metaplex repo. In essence it came down to locking in the old typescript versions in the package.lock json. Please note that the followimg ONLY applies to the older version of metaplex. 

In short: it was a matter of removing the '^' from the package.json's ts-node and typescript entries. I assume something similar applies to the new repo. I might try to explore this a little later today if I have time.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/6106392/179429256-8e8e8612-8bd1-4fd5-861a-a183229c98c8.png">

**Comment by MyNameisLeon** [comment]
I have the same issue, but for me the workaround of @mnedelko is not working in the new repo...
Is there any way to fix it using the new gumdrop repo?

**Comment by MarkSackerberg** [comment]
Just for your information: The Gumdrop that has already been created where the error above happens. Also all the info you need (URLs, Base file) have been created.

You are receiving the error when for other distribution methods than manual and wallets the URLs would be send out via mail/SMS/Discord.

In short: Ignore the error for now. At least for distribution method Wallets everything is working as it should (Just the error message that is shown is incorrect)
